name = "Another Worlds Unofficial"
author = "alexyzer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4a9641587fd51de183a08403fb63c25c2776c50727cda08e0cf706e087e59be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
