name = "Another Worlds Unofficial"
author = "alexyzer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b9c88d019b157b44816b3d23944bb1f0037feabd30c4ba4b1df226a51d9857c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
