name = "Another Worlds Unofficial"
author = "alexyzer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61dea3368ff19de792756fe671b8afe6994c4c4fad056130e795a6409d8fa545"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
